<a href="https://colab.research.google.com/github/tasha2017/Projects/blob/main/Multiple_Linear_Regression_with_Climate_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [8]:
dataset = pd.read_csv('ClimateData.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
print(X)

[[0.48051205 0.52656904 0.71693249]
 [0.40824314 0.31074415 0.56595727]
 [0.32653836 0.31749554 0.54290817]
 [0.24701918 0.         0.        ]
 [0.54306345 0.2793509  0.73743606]
 [0.47158985 0.34046181 0.65757222]
 [0.47045759 0.30666793 0.44476178]
 [0.3374325  0.36101932 0.49095739]
 [0.47970187 0.1908613  0.31495875]
 [0.35039808 0.29437052 0.29710223]
 [0.35142566 0.35077846 0.46493997]
 [0.42735586 0.33894239 0.        ]
 [0.41777239 0.49496565 0.45940155]
 [0.51871186 0.44998246 0.66628051]
 [0.39621585 0.37088976 0.42729207]
 [0.32618209 0.32949075 0.39052003]
 [0.34025224 0.41749985 0.31632509]
 [0.47225174 0.41987154 0.61004241]
 [0.44695639 0.57849761 0.75397253]
 [0.48491887 0.33871897 0.63406205]
 [0.44837651 0.32621916 0.66251489]
 [0.35742431 0.26596236 0.49512203]
 [0.35648948 0.41079593 0.6307855 ]
 [0.50133621 0.26875765 0.44709097]
 [0.40478452 0.19934057 0.54831821]
 [0.38239743 0.29815379 0.38157405]
 [0.52887725 0.41536346 0.71991583]
 [0.52231529 0.50512005 0.77

## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [12]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0.39 0.57]
 [0.5  0.75]
 [0.43 0.33]
 [0.42 0.21]
 [0.23 0.31]
 [0.32 0.23]
 [0.31 0.33]
 [0.3  0.42]
 [0.62 0.48]
 [0.46 0.5 ]
 [0.34 0.45]
 [0.48 0.51]
 [0.24 0.23]
 [0.43 0.48]
 [0.55 0.55]
 [0.41 0.23]
 [0.34 0.28]
 [0.41 0.54]
 [0.51 0.6 ]
 [0.34 0.34]
 [0.3  0.3 ]
 [0.44 0.18]
 [0.37 0.34]
 [0.53 0.71]
 [0.33 0.2 ]
 [0.38 0.47]
 [0.56 0.72]
 [0.35 0.29]
 [0.35 0.4 ]
 [0.23 0.17]
 [0.29 0.25]
 [0.46 0.64]
 [0.28 0.28]
 [0.5  0.52]
 [0.55 0.57]
 [0.3  0.28]
 [0.54 0.57]
 [0.46 0.41]
 [0.45 0.41]]
